server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  datasource:
    url: jdbc:mysql:///mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
